name: conecta_lsb
description: "Conecta LSB - Comunicación accesible con traducción de Lengua de Señas Boliviana"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^4.2.2
  speech_to_text: ^7.2.0
  google_fonts: ^6.2.1
  appwrite: ^13.0.0
  uuid: ^4.3.3
  flutter_web_auth_2: ^5.0.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  google_mlkit_pose_detection: ^0.13.0
  http: ^1.2.2
  path_provider: ^2.1.4
  web_socket_channel: ^3.0.3
  audioplayers: ^6.7.1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^20.1.0
  image: ^4.8.0
  flutter_webrtc: ^1.5.2

dependency_overrides:
  flutter_web_auth_2: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/msl/terms.txt
    - assets/msl/terms_sample.txt
    - assets/msl/vocabulary.json
    - assets/msl/guia_senas.png
    - assets/sounds/ringtone.wav

